spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  flyway:
    baselineOnMigrate: true
    # 如果指定 schema 包含了其他表但没有 flyway schema history 表的话，在执行 flyway migrate 命令之前须先执行 flyway baseline 命令。
    # 设置 spring.flyway.baseline-on-migrate 为 true 后，flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baselineVersion: 0.0.1
    cleanDisabled: true # flyway 的 clean 命令会删除指定 schema 下的所有 table，应该禁掉
    enabled: true # 启用或禁用 flyway
    locations: classpath:db/migration # 设定 SQL 脚本的目录，比如取值为 classpath:db/migration,filesystem:/sql-migrations
    outOfOrder: false # 生产环境关闭 outOfOrder

#elasticsearch:
#  transaction-event-index-prefix: "main.0727"

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
