server:
  port: 8787
  max-http-header-size: 102400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${STARCOIN_MYSQL_URL}
    username: ${STARCOIN_MYSQL_USER}
    password: ${STARCOIN_MYSQL_PWD}

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    baselineOnMigrate: true
    # 如果指定 schema 包含了其他表但没有 flyway schema history 表的话，在执行 flyway migrate 命令之前须先执行 flyway baseline 命令。
    # 设置 spring.flyway.baseline-on-migrate 为 true 后，flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baselineVersion: 0.0.1
    cleanDisabled: true # flyway 的 clean 命令会删除指定 schema 下的所有 table，应该禁掉
    enabled: true # 启用或禁用 flyway
    locations: classpath:db/migration # 设定 SQL 脚本的目录，比如取值为 classpath:db/migration,filesystem:/sql-migrations
    outOfOrder: false # 生产环境关闭 outOfOrder
    #spring.flyway.encoding=
    # Encoding of SQL migrations (default: UTF-8)
    #spring.flyway.schemas=
    # 需要 flyway 管控的 schema list，缺省的使用 dbsource.connection 直连上的那个 schema，
    # 可以指定多个schema，但仅会在第一个 schema 下建立 metadata 表，也仅在第一个 schema 应用 migration sql 脚本，
    # 但 flyway clean 命令会依次在这些 schema 下都执行一遍。

#  jackson:
#    serialization:
#      write_dates_as_timestamps: false

  security:
    htpasswd: ${SPRING_SECURITY_HTPASSWD}


jasypt:
  encryptor:
    bean: encryptorBean
    password: ${STARCOIN_ES_PWD}


elasticsearch:
  host: ${STARCOIN_ES_URL}
  protocol: ${STARCOIN_ES_PROTOCOL}
  port: ${STARCOIN_ES_PORT}
  username: ${STARCOIN_ES_USER}
  connTimeout: 10000
  socketTimeout: 10000
  connectionRequestTimeout: 2000
  transaction-event-index-prefix: ${STARCOIN_ES_TXN_EVENT_IDX_PREFIX}


airdrop:
  vote-reward-process-task-service:
    fixed-delay: 10000


starcoin:
  # seeds: ${STARCOIN_SEEDS}
  network: ${STARCOIN_NETWORK}
  json-rpc-url: ${STARCOIN_JSON_RPC_URL}
  chain-id: ${STARCOIN_CHAIN_ID}
  airdrop:
    token-type: "0x00000000000000000000000000000001::STC::STC"
    function-address: "0xb987F1aB0D7879b2aB421b98f96eFb44"
    owner-private-key: ${STARCOIN_AIRDROP_OWNER_PK}
  get-last-proposal-list-url: https://poll-api.starcoin.org/v1/polls/page/main?page=1
  vote-reward-name-prefix-format: "投票#%1$s奖励-"
  vote-reward-name-en-prefix-format: "Award of Poll#%1$s-"

ok:
  http:
    connect-timeout: 10
    max-idle-connections: 60
    read-timeout: 10
    write-timeout: 10
    keep-alive-duration: 600


springfox:
  documentation:
    swaggerUi:
      baseUrl: /airdrop-api-doc
    openApi:
      v3:
        path: /airdrop-api-doc/v3/api-docs
    swagger:
      v2:
        path: /airdrop-api-doc/v2/api-docs
